apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: frontend-active
      previewService: frontend-preview
      autoPromotionEnabled: true
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/ziyadtarek99/frontend:latest
        imagePullPolicy: Always
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://k8s-threetie-mainlb-82c1e104b4-1551491477.us-east-1.elb.amazonaws.com/api/tasks"
        ports:
        - containerPort: 3000
