apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ziyad-tarek1/Full-DevSecOps-Project-blue-green-deployments.git'
    targetRevision: HEAD
    path: k8s/Ingress
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: three-tier
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
